### ISSUE TITLE
Day of Week issue

### ISSUE THREAD

**Issue by Edeoinc** [safx/CronExpression-swift#2]
Thank you for latest fix!
But i believe it prevent to proper detection days of week.

For example expression:
`0 0 12 ? * SUN *`
returns nil
And 
`0 0 12 ? * MON *`
return first day of next mouth
`0 0 12 ? * THU *`
return today 12:00
`0 0 12 ? * FRI *`
return next day 12:00

**Comment by safx** [comment]
I found another misfunction, which has been fixed.
Thanks.
